//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP5WebTransactionnel.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP5WebTransactionnel.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès interdit, veuillez vous connecter avec un autre utilisateur..
        /// </summary>
        public static string AccessDeniedChangeUserMsg {
            get {
                return ResourceManager.GetString("AccessDeniedChangeUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accès interdit, veuillez vous connecter..
        /// </summary>
        public static string AccessDeniedMsg {
            get {
                return ResourceManager.GetString("AccessDeniedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un membre.
        /// </summary>
        public static string AddMembre {
            get {
                return ResourceManager.GetString("AddMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ADMINISTRATION.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page d&apos;accueil.
        /// </summary>
        public static string BackToHomepage {
            get {
                return ResourceManager.GetString("BackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la page de connexion.
        /// </summary>
        public static string BackToLoginPage {
            get {
                return ResourceManager.GetString("BackToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES CHOIX DE MENU.
        /// </summary>
        public static string ChoiMenu {
            get {
                return ResourceManager.GetString("ChoiMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix du menu.
        /// </summary>
        public static string ChoixMenu {
            get {
                return ResourceManager.GetString("ChoixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer la réservation.
        /// </summary>
        public static string ConfirmReserv {
            get {
                return ResourceManager.GetString("ConfirmReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau compte.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de réservation.
        /// </summary>
        public static string DateReserv {
            get {
                return ResourceManager.GetString("DateReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;équipe.
        /// </summary>
        public static string Equipe {
            get {
                return ResourceManager.GetString("Equipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identification.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de courriel invalide..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur et/ou mot de passe incorrect(s)..
        /// </summary>
        public static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES MEMBRES.
        /// </summary>
        public static string LesMembres {
            get {
                return ResourceManager.GetString("LesMembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LES RÉSERVATIONS.
        /// </summary>
        public static string LesReserv {
            get {
                return ResourceManager.GetString("LesReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listes des membres.
        /// </summary>
        public static string ListChoixMembre {
            get {
                return ResourceManager.GetString("ListChoixMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des choix de menu.
        /// </summary>
        public static string ListChoixMenu {
            get {
                return ResourceManager.GetString("ListChoixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listes des réservatisons.
        /// </summary>
        public static string ListReserv {
            get {
                return ResourceManager.GetString("ListReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur doit être entre {1} et {2}..
        /// </summary>
        public static string ModelBetween {
            get {
                return ResourceManager.GetString("ModelBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur doit être entre {2} et {1}..
        /// </summary>
        public static string ModelLengthBetween {
            get {
                return ResourceManager.GetString("ModelLengthBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La longueur doit être plus petite que {1}..
        /// </summary>
        public static string ModelLengthLessThan {
            get {
                return ResourceManager.GetString("ModelLengthLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur doit être un nombre..
        /// </summary>
        public static string ModelNumber {
            get {
                return ResourceManager.GetString("ModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} obligatoire..
        /// </summary>
        public static string ModelRequired {
            get {
                return ResourceManager.GetString("ModelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom existe déjà..
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de client.
        /// </summary>
        public static string NbClient {
            get {
                return ResourceManager.GetString("NbClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prendre Réservation.
        /// </summary>
        public static string PrendreReserv {
            get {
                return ResourceManager.GetString("PrendreReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous certain de vouloir supprimer ce membre?.
        /// </summary>
        public static string QuestionSuppMember {
            get {
                return ResourceManager.GetString("QuestionSuppMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes-vous certain de vouloir supprimer ce menu?.
        /// </summary>
        public static string QuestionSuppMenu {
            get {
                return ResourceManager.GetString("QuestionSuppMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservation complété avec succès.
        /// </summary>
        public static string ReservComp {
            get {
                return ResourceManager.GetString("ReservComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RÉSERVATION EN LIGNE.
        /// </summary>
        public static string ReservLigne {
            get {
                return ResourceManager.GetString("ReservLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste de membre.
        /// </summary>
        public static string RetournMembre {
            get {
                return ResourceManager.GetString("RetournMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste des choix de menu.
        /// </summary>
        public static string RetournMenu {
            get {
                return ResourceManager.GetString("RetournMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner à la page d&apos;accueil.
        /// </summary>
        public static string ReturnPage {
            get {
                return ResourceManager.GetString("ReturnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste des réservation.
        /// </summary>
        public static string ReturnReserv {
            get {
                return ResourceManager.GetString("ReturnReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Supp {
            get {
                return ResourceManager.GetString("Supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un membre.
        /// </summary>
        public static string SuppMembre {
            get {
                return ResourceManager.GetString("SuppMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer un choix de menu.
        /// </summary>
        public static string SuppMenu {
            get {
                return ResourceManager.GetString("SuppMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une réservation.
        /// </summary>
        public static string SuppReserv {
            get {
                return ResourceManager.GetString("SuppReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;avoir utiliser notre modure de réservation en ligne..
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à un choix de menu.
        /// </summary>
        public static string UnChoixMenu {
            get {
                return ResourceManager.GetString("UnChoixMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à un membre.
        /// </summary>
        public static string UnMembre {
            get {
                return ResourceManager.GetString("UnMembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au plaisir de vous voir bientôt.
        /// </summary>
        public static string VoirBiento {
            get {
                return ResourceManager.GetString("VoirBiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre réservation .
        /// </summary>
        public static string VotreReserv {
            get {
                return ResourceManager.GetString("VotreReserv", resourceCulture);
            }
        }
    }
}
